site_name:           CapAndHomalg.jl
repo_url:            https://github.com/homalg-project/CapAndHomalg.jl
site_description:    The CAP and homalg projects compatibility package for Julia
site_author:         Mohamed Barakat <mohamed.barakat@uni-siegen.de>
theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math # For LaTeX

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
